services:
  taskmaster:
    build: .
    ports:
      - "6274:6274"  # MCP Inspector UI
      - "6278:6278"  # HTTP Server
      - "6277:6277"  # MCP Inspector Proxy
    volumes:
      - taskdata:/app/data  # Use named volume for data
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 6274 && nc -z localhost 6278 && nc -z localhost 6277"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    user: taskmaster

volumes:
  taskdata:  # Define named volume for persistence