version: '3.8'

services:
  taskmaster:
    build: .
    ports:
      - "0.0.0.0:6274:6274"  # MCP Inspector UI
      - "0.0.0.0:6277:6277"  # SSE Transport
    volumes:
      - taskdata:/app/data  # Use named volume for data
    healthcheck:
      test: ["CMD-SHELL", "nc -z 0.0.0.0 6274 && nc -z 0.0.0.0 6277 && test -w /app/data/tasks.json"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      - MCP_INSPECTOR_HOST=0.0.0.0
      - MCP_SSE_HOST=0.0.0.0
    user: taskmaster  # Explicitly set the user
    networks:
      - mcp_network

networks:
  mcp_network:
    driver: bridge

volumes:
  taskdata:  # Define named volume for persistence