version: '3.8'

services:
  taskmaster:
    build: .
    ports:
      - "0.0.0.0:6274:6274"  # MCP Inspector UI
      - "0.0.0.0:6277:6277"  # Proxy Server
    volumes:
      - taskdata:/app/data  # Use named volume for data
    healthcheck:
      test: ["CMD-SHELL", "nc -z 0.0.0.0 6274 && nc -z 0.0.0.0 6277 && test -w /app/data/tasks.json"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    user: taskmaster  # Explicitly set the user

volumes:
  taskdata:  # Define named volume for persistence